<a href="https://colab.research.google.com/github/boryslawskamaria/ML_scripts/blob/main/breast_cancer_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Models written to decide if a given patient probably has malignant breast cancer.


---

1.   No hidden layers
2.   1 hidden layer and 2 nodes
3.   1 hidden layer and 4 nodes
4.   1 hidden layer and 10 nodes


In [8]:
import pandas as pd
import numpy as np
from  sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score
from sklearn import linear_model

url=('https://raw.githubusercontent.com/boryslawskamaria/ML_scripts/main/wbca.csv')

A=pd.read_csv(url)

In [9]:
X=A[["Adhes","BNucl","Chrom","Epith","Mitos","NNucl","Thick","UShap","USize"]] 
Y=A['Class']
y=np.asarray(Y,dtype=np.float64)
x=np.asarray(X)

mlp=MLPClassifier(hidden_layer_sizes=(),activation='logistic',max_iter=5000)
mlp.fit(x, y)
Z=mlp.predict(x)

print("Zero hidden layers: \n" ,confusion_matrix(y, Z),  "\n f1 =", f1_score(y,Z), "\n accuracy =",accuracy_score(y,Z), "\n")

mlp=MLPClassifier(hidden_layer_sizes=(2),activation='logistic',max_iter=5000)
mlp.fit(x, y)
Z=mlp.predict(x)

print("1 hidden layer with 2 knots: \n" ,confusion_matrix(y, Z),  "\n f1 =", f1_score(y,Z), "\n accuracy =",accuracy_score(y,Z), "\n")

mlp=MLPClassifier(hidden_layer_sizes=(4),activation='logistic',max_iter=5000)
mlp.fit(x, y)
Z=mlp.predict(x)

print("1 hidden layer with 4 knots: \n" ,confusion_matrix(y, Z),  "\n f1 =", f1_score(y,Z), "\n accuracy =",accuracy_score(y,Z), "\n")

mlp=MLPClassifier(hidden_layer_sizes=(10),activation='logistic',max_iter=5000)
mlp.fit(x, y)
Z=mlp.predict(x)

print("1 hidden layer with 10 knots: \n" ,confusion_matrix(y, Z),  "\n f1 =", f1_score(y,Z), "\n accuracy =",accuracy_score(y,Z), "\n")

A=linear_model.LogisticRegression(C=10)
A.fit(x, y)
Z=A.predict(x)

print("Logistic regression: \n" ,confusion_matrix(y, Z),  "\n f1 =", f1_score(y,Z), "\n accuracy =",accuracy_score(y,Z), "\n")


Zero hidden layers: 
 [[225  13]
 [  9 434]] 
 f1 = 0.9752808988764043 
 accuracy = 0.9676945668135095 

1 hidden layer with 2 knots: 
 [[230   8]
 [ 11 432]] 
 f1 = 0.9784824462061155 
 accuracy = 0.9720998531571219 

1 hidden layer with 4 knots: 
 [[230   8]
 [ 10 433]] 
 f1 = 0.9796380090497738 
 accuracy = 0.973568281938326 

1 hidden layer with 10 knots: 
 [[231   7]
 [  9 434]] 
 f1 = 0.9819004524886877 
 accuracy = 0.9765051395007343 

Logistic regression: 
 [[228  10]
 [  9 434]] 
 f1 = 0.9785794813979707 
 accuracy = 0.9720998531571219 

