<a href="https://colab.research.google.com/github/boryslawskamaria/ML_scripts/blob/main/oil_export_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Models are created to decide whether a given country exports oil.

In [12]:
import pandas as pd
import numpy as np
from  sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score
from sklearn import linear_model

url='https://raw.githubusercontent.com/boryslawskamaria/ML_scripts/main/infmort.csv'

A=pd.read_csv(url)


In [13]:
A=A.dropna()
X=A[["income", "mortality"]] 
Y=A['oil']
Y[Y=="no oil exports"]=0
Y[Y=="oil exports"]=1
y=np.asarray(Y,dtype=np.float64)
x=np.asarray(X)

mlp=MLPClassifier(hidden_layer_sizes=(),activation='logistic',max_iter=5000)
mlp.fit(x, y)
Z=mlp.predict(x)

print("Zero hidden layers: \n" ,confusion_matrix(y, Z),  "\n f1 =", f1_score(y,Z), "\n prediction accuracy =",accuracy_score(y,Z), "\n")

mlp=MLPClassifier(hidden_layer_sizes=(2),activation='logistic',max_iter=5000)
mlp.fit(x, y)
Z=mlp.predict(x)

print("1 hidden layer with 2 knots: \n" ,confusion_matrix(y, Z),  "\n f1 =", f1_score(y,Z), "\n % of prediction accuracy =",accuracy_score(y,Z), "\n")

mlp=MLPClassifier(hidden_layer_sizes=(4),activation='logistic',max_iter=5000)
mlp.fit(x, y)
Z=mlp.predict(x)

print("1 hidden layer with 4 knots: \n" ,confusion_matrix(y, Z),  "\n f1 =", f1_score(y,Z), "\n % of prediction accuracy =",accuracy_score(y,Z), "\n")

mlp=MLPClassifier(hidden_layer_sizes=(10),activation='logistic',max_iter=5000)
mlp.fit(x, y)
Z=mlp.predict(x)

print("1 hidden layer with 10 knotsi: \n" ,confusion_matrix(y, Z),  "\n f1 =", f1_score(y,Z), "\n % of prediction accuracy =",accuracy_score(y,Z), "\n")

A=linear_model.LogisticRegression(C=10)
A.fit(x, y)
Z=A.predict(x)

print("Logistic regression: \n" ,confusion_matrix(y, Z),  "\n f1 =", f1_score(y,Z), "\n % of prediction accuracy =",accuracy_score(y,Z), "\n")

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


Zero hidden layers: 
 [[93  0]
 [ 8  0]] 
 f1 = 0.0 
 prediction accuracy = 0.9207920792079208 

1 hidden layer with 2 knots: 
 [[93  0]
 [ 8  0]] 
 f1 = 0.0 
 % of prediction accuracy = 0.9207920792079208 

1 hidden layer with 4 knots: 
 [[93  0]
 [ 8  0]] 
 f1 = 0.0 
 % of prediction accuracy = 0.9207920792079208 

1 hidden layer with 10 knotsi: 
 [[93  0]
 [ 8  0]] 
 f1 = 0.0 
 % of prediction accuracy = 0.9207920792079208 

Logistic regression: 
 [[93  0]
 [ 7  1]] 
 f1 = 0.2222222222222222 
 % of prediction accuracy = 0.9306930693069307 

